services:
  mpi:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/mpi:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./mpi
    container_name: mpi

  openmpi:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/openmpi:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./openmpi
    container_name: openmpi

  openmpi-builder:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/openmpi-builder:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./openmpi-builder
    container_name: openmpi-builder

  lammps-openmpi:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/lammps-openmpi:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./lammps-openmpi
    container_name: lammps-openmpi

