services:
  mpi:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/mpi:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./mpi
    container_name: mpi

  mpi-ubuntu:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/mpi-ubuntu:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./mpi-ubuntu
    container_name: mpi-ubuntu

  openmpi:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/openmpi:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./openmpi
    container_name: openmpi

  openmpi-ubuntu:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/openmpi-ubuntu:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./openmpi-ubuntu
    container_name: openmpi-ubuntu

  openmpi-builder:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/openmpi-builder:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./openmpi-builder
    container_name: openmpi-builder

  openmpi-builder-ubuntu:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/openmpi-builder-ubuntu:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./openmpi-builder-ubuntu
    container_name: openmpi-builder-ubuntu

  lammps-openmpi:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/lammps-openmpi:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./lammps-openmpi
    container_name: lammps-openmpi
  
  gromacs-openmpi:
    image: ${SHOC_CONTAINERS_CR:-ghcr.io}/${SHOC_CONTAINERS_REPO:-shoc-dev/containers/library}/gromacs-openmpi:${SHOC_CONTAINERS_VERSION:-latest}
    build: ./gromacs-openmpi
    container_name: gromacs-openmpi

