name: Publish Docker Images

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to build and push'
        required: true
        type: choice
        options:
          - mpi
          - openmpi
      version:
        description: 'Image version tag'
        required: false
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      SHOC_CONTAINERS_CR: ghcr.io
      SHOC_CONTAINERS_REPO: shoc-dev/containers/library
      SHOC_CONTAINERS_VERSION: ${{ inputs.version }}
      SHOC_SERVICE_NAME: ${{ inputs.service }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.SHOC_CONTAINERS_CR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          use: true

      - name: Build and push multi-arch image
        working-directory: ./library
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${SHOC_CONTAINERS_CR}/${SHOC_CONTAINERS_REPO}/$SHOC_SERVICE_NAME:$SHOC_CONTAINERS_VERSION \
            --push \
            ./$SHOC_SERVICE_NAME
            
