name: Publish Docker Images

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to build and push'
        required: true
        type: choice
        options:
          - mpi
          - openmpi
      version:
        description: 'Image version tag'
        required: false
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      SHOC_CONTAINERS_CR: ghcr.io
      SHOC_CONTAINERS_REPO: shoc/dev/containers/library
      SHOC_CONTAINERS_VERSION: ${{ inputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.SHOC_CONTAINERS_CR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the image using compose
        working-directory: ./library
        run: |
          docker compose build ${{ inputs.service }}

      - name: Push the image with compose
        working-directory: ./library
        run: |
          docker compose push ${{ inputs.service }}
